INSERT INTO Allergen(ID,name,code)VALUES ('1','Glutenhaltiges Getreide','A');
INSERT INTO Allergen(ID,name,code)VALUES ('2','Krebstiere und daraus gewonnene Erzeugnisse','B');
INSERT INTO Allergen(ID,name,code)VALUES ('3','Eier und Geflügel und daraus gewonnene Erzeugnisse','C');
INSERT INTO Allergen(ID,name,code)VALUES ('4','Fisch und daraus gewonnene Erzeugnisse (ausser Fischgelatine)','D');
INSERT INTO Allergen(ID,name,code)VALUES ('5','Erdnüsse und daraus gewonnene Erzeugnisse','E');
INSERT INTO Allergen(ID,name,code)VALUES ('6','Sojabohnen und daraus gewonnene Erzeugnisse','F');
INSERT INTO Allergen(ID,name,code)VALUES ('7','Milch von Säugetieren und Milcherzeugnisse (inklusive Laktose)','G');
INSERT INTO Allergen(ID,name,code)VALUES ('8','Schalenfrüchte und daraus gewonnene Erzeugnisse','H');
INSERT INTO Allergen(ID,name,code)VALUES ('9','Sellerie und daraus gewonnene Erzeugnisse','L');
INSERT INTO Allergen(ID,name,code)VALUES ('10','Senf und daraus gewonnene Erzeugnisse','M');
INSERT INTO Allergen(ID,name,code)VALUES ('11','Sesamsamen und daraus gewonnene Erzeugnisse','N');
INSERT INTO Allergen(ID,name,code)VALUES ('12','Schwefeldioxid und Sulfite','O');
INSERT INTO Allergen(ID,name,code)VALUES ('13','Lupinen und daraus gewonnene Erzeugnisse','P');
INSERT INTO Allergen(ID,name,code)VALUES ('14','Weichtiere wie Schnecken, Muscheln, Tintenfische und daraus gewonnene Erzeugnisse','R');
INSERT INTO Allergen(ID,name,code)VALUES ('-1','Kein Allergen', '');