INSERT INTO INGREDIENTCATEGORY (NAME,DESCRIPTION)
VALUES ('Gemüse','');

INSERT INTO INGREDIENTCATEGORY (NAME,DESCRIPTION)
VALUES ('Milchprodukt','');

INSERT INTO INGREDIENTCATEGORY (NAME,DESCRIPTION)
VALUES ('Gemüse (scharf)','');


INSERT INTO INGREDIENTCATEGORY (NAME,DESCRIPTION)
VALUES ('Kräuter','');

INSERT INTO INGREDIENTCATEGORY (NAME,DESCRIPTION)
VALUES ('Brot','');

INSERT INTO INGREDIENTCATEGORY (NAME,DESCRIPTION)
VALUES ('Fleisch','');

INSERT INTO INGREDIENTCATEGORY (NAME,DESCRIPTION)
VALUES ('Fisch','');

INSERT INTO INGREDIENTCATEGORY (NAME,DESCRIPTION)
VALUES ('Nudeln','');

INSERT INTO INGREDIENTCATEGORY (NAME,DESCRIPTION)
VALUES ('Obst','');

INSERT INTO INGREDIENTCATEGORY (NAME,DESCRIPTION)
VALUES ('Essig','');

INSERT INTO INGREDIENTCATEGORY (NAME,DESCRIPTION)
VALUES ('Öl','');

INSERT INTO INGREDIENTCATEGORY (NAME,DESCRIPTION)
VALUES ('Marlmelade','');

INSERT INTO INGREDIENTCATEGORY (NAME,DESCRIPTION)
VALUES ('Gewürz','');

INSERT INTO INGREDIENTCATEGORY (NAME,DESCRIPTION)
VALUES ('Kornprodukt','');

INSERT INTO INGREDIENTCATEGORY (NAME,DESCRIPTION)
VALUES ('Suppe','');

INSERT INTO INGREDIENTCATEGORY (NAME,DESCRIPTION)
VALUES ('Bohnen','');

INSERT INTO INGREDIENTCATEGORY (NAME,DESCRIPTION)
VALUES ('Sauce','');

INSERT INTO INGREDIENTCATEGORY (NAME,DESCRIPTION)
VALUES ('Teigware','');

INSERT INTO INGREDIENTCATEGORY (NAME,DESCRIPTION)
VALUES ('Zitrus','');

INSERT INTO INGREDIENTCATEGORY (NAME,DESCRIPTION)
VALUES ('Pilze','');

INSERT INTO INGREDIENTCATEGORY (NAME,DESCRIPTION)
VALUES ('Innerei','');

INSERT INTO INGREDIENTCATEGORY (NAME,DESCRIPTION)
VALUES ('Alkoholhaltiges','');

INSERT INTO INGREDIENTCATEGORY (NAME,DESCRIPTION)
VALUES ('Zwiebel','');

INSERT INTO INGREDIENTCATEGORY (NAME,DESCRIPTION)
VALUES ('Stärke','');

INSERT INTO INGREDIENTCATEGORY (NAME,DESCRIPTION)
VALUES ('Meeresfrüchte','');

INSERT INTO INGREDIENTCATEGORY (NAME,DESCRIPTION)
VALUES ('Nektar','');

INSERT INTO INGREDIENTCATEGORY (NAME,DESCRIPTION)
VALUES ('Sesam','');

INSERT INTO INGREDIENTCATEGORY (NAME,DESCRIPTION)
VALUES ('Sirup','');

INSERT INTO INGREDIENTCATEGORY (NAME,DESCRIPTION)
VALUES ('Soja','');

INSERT INTO INGREDIENTCATEGORY (NAME,DESCRIPTION)
VALUES ('Reis','');

INSERT INTO INGREDIENTCATEGORY (NAME,DESCRIPTION)
VALUES ('Wasser','');

INSERT INTO INGREDIENTCATEGORY (NAME,DESCRIPTION)
VALUES ('Ei','');
