INSERT INTO INGREDIENTCATEGORY (ID,NAME,DESCRIPTION)
VALUES ('1','Gemüse','');

INSERT INTO INGREDIENTCATEGORY (ID,NAME,DESCRIPTION)
VALUES ('2','Milchprodukt','');

INSERT INTO INGREDIENTCATEGORY (ID,NAME,DESCRIPTION)
VALUES ('3','Gemüse (scharf)','');


INSERT INTO INGREDIENTCATEGORY (ID,NAME,DESCRIPTION)
VALUES ('4','Kräuter','');

INSERT INTO INGREDIENTCATEGORY (ID,NAME,DESCRIPTION)
VALUES ('5','Brot','');

INSERT INTO INGREDIENTCATEGORY (ID,NAME,DESCRIPTION)
VALUES ('6','Fleisch','');

INSERT INTO INGREDIENTCATEGORY (ID,NAME,DESCRIPTION)
VALUES ('7','Fisch','');

INSERT INTO INGREDIENTCATEGORY (ID,NAME,DESCRIPTION)
VALUES ('8','Nudeln','');

INSERT INTO INGREDIENTCATEGORY (ID,NAME,DESCRIPTION)
VALUES ('9','Obst','');

INSERT INTO INGREDIENTCATEGORY (ID,NAME,DESCRIPTION)
VALUES ('10','Essig','');

INSERT INTO INGREDIENTCATEGORY (ID,NAME,DESCRIPTION)
VALUES ('11','Öl','');

INSERT INTO INGREDIENTCATEGORY (ID,NAME,DESCRIPTION)
VALUES ('12','Marlmelade','');

INSERT INTO INGREDIENTCATEGORY (ID,NAME,DESCRIPTION)
VALUES ('13','Gewürz','');

INSERT INTO INGREDIENTCATEGORY (ID,NAME,DESCRIPTION)
VALUES ('14','Kornprodukt','');

INSERT INTO INGREDIENTCATEGORY (ID,NAME,DESCRIPTION)
VALUES ('15','Suppe','');

INSERT INTO INGREDIENTCATEGORY (ID,NAME,DESCRIPTION)
VALUES ('16','Bohnen','');

INSERT INTO INGREDIENTCATEGORY (ID,NAME,DESCRIPTION)
VALUES ('17','Sauce','');

INSERT INTO INGREDIENTCATEGORY (ID,NAME,DESCRIPTION)
VALUES ('18','Teigware','');

INSERT INTO INGREDIENTCATEGORY (ID,NAME,DESCRIPTION)
VALUES ('19','Zitrus','');

INSERT INTO INGREDIENTCATEGORY (ID,NAME,DESCRIPTION)
VALUES ('20','Pilze','');

INSERT INTO INGREDIENTCATEGORY (ID,NAME,DESCRIPTION)
VALUES ('21','Innerei','');

INSERT INTO INGREDIENTCATEGORY (ID,NAME,DESCRIPTION)
VALUES ('22','Alkoholhaltiges','');

INSERT INTO INGREDIENTCATEGORY (ID,NAME,DESCRIPTION)
VALUES ('23','Zwiebel','');

INSERT INTO INGREDIENTCATEGORY (ID,NAME,DESCRIPTION)
VALUES ('24','Stärke','');

INSERT INTO INGREDIENTCATEGORY (ID,NAME,DESCRIPTION)
VALUES ('25','Meeresfrüchte','');

INSERT INTO INGREDIENTCATEGORY (ID,NAME,DESCRIPTION)
VALUES ('26','Nektar','');

INSERT INTO INGREDIENTCATEGORY (ID,NAME,DESCRIPTION)
VALUES ('27','Sesam','');

INSERT INTO INGREDIENTCATEGORY (ID,NAME,DESCRIPTION)
VALUES ('28','Sirup','');

INSERT INTO INGREDIENTCATEGORY (ID,NAME,DESCRIPTION)
VALUES ('29','Soja','');

INSERT INTO INGREDIENTCATEGORY (ID,NAME,DESCRIPTION)
VALUES ('30','Reis','');

INSERT INTO INGREDIENTCATEGORY (ID,NAME,DESCRIPTION)
VALUES ('31','Wasser','');

INSERT INTO INGREDIENTCATEGORY (ID,NAME,DESCRIPTION)
VALUES ('32','Ei','');
