INSERT INTO USERACCOUNT(ID,EMAIL,FIRSTNAME,LASTNAME,PASSWORD,PROFILEPICTURE)VALUES ('1','hilda.tellioglu@tuwien.ac.at','Hilda','Tellioglu',null,null );
INSERT INTO USERACCOUNT(ID,EMAIL,FIRSTNAME,LASTNAME,PASSWORD,PROFILEPICTURE)VALUES ('2','peter.fikar@tuwien.ac.at','Peter','Fikar',null,null);
INSERT INTO USERACCOUNT(ID,EMAIL,FIRSTNAME,LASTNAME,PASSWORD,PROFILEPICTURE)VALUES ('3',null,'Georg','Edlinger',null,null);
INSERT INTO USERACCOUNT(ID,EMAIL,FIRSTNAME,LASTNAME,PASSWORD,PROFILEPICTURE)VALUES ('4',null,'Bastian','Christ',null,null);

INSERT INTO USERSCALEASSIGNMENT (ID, USERID, SCALE_ONE, SCALE_TWO, SCALE_THREE, SCALE_FOUR, SCALE_FIVE, SCALE_SIX) VALUES (1,1,1,2,3,4,5,6);
INSERT INTO USERSCALEASSIGNMENT (ID, USERID, SCALE_ONE, SCALE_TWO, SCALE_THREE, SCALE_FOUR, SCALE_FIVE, SCALE_SIX) VALUES (2,2,1,2,3,4,5,6);
INSERT INTO USERSCALEASSIGNMENT (ID, USERID, SCALE_ONE, SCALE_TWO, SCALE_THREE, SCALE_FOUR, SCALE_FIVE, SCALE_SIX) VALUES (3,3,1,2,3,4,5,6);
INSERT INTO USERSCALEASSIGNMENT (ID, USERID, SCALE_ONE, SCALE_TWO, SCALE_THREE, SCALE_FOUR, SCALE_FIVE, SCALE_SIX) VALUES (4,4,1,2,3,4,5,6);

INSERT INTO USERALLERGIES (ID,ALLERGYID,DATEADDED,USERID) VALUES ('1','1','19-06-2018',1);
INSERT INTO USERALLERGIES (ID,ALLERGYID,DATEADDED,USERID) VALUES ('2','2','19-06-2018',1);
INSERT INTO USERALLERGIES (ID,ALLERGYID,DATEADDED,USERID) VALUES ('3','2','19-06-2018',2);

INSERT INTO RECIPEHISTORY(ID, USERID,RECIPEID,COOKEDON) VALUES (1,1,1,'19-06-2018');

INSERT INTO FAVORITERECIPE (ID,USERID,RECIPEID,FAVORITEDON) VALUES (1,1,15,'19-06-2018');
