INSERT INTO INGREDIENT (ID,name, category) VALUES ('1','Mehl (glatt)','Kornprodukt');
INSERT INTO INGREDIENT (ID,name, category) VALUES ('2','Eier','Ei');
INSERT INTO INGREDIENT (ID,name, category) VALUES ('3','Milch','Milchprodukt');
INSERT INTO INGREDIENT (ID,name, category) VALUES ('4','Butter (geschmolzen)','Milchprodukt');
INSERT INTO INGREDIENT (ID,name, category) VALUES ('5','Salz','Gewürz');
INSERT INTO INGREDIENT (ID,name, category) VALUES ('6','EL Butter (zerlassen, zum Herausbacken)','Milchprodukt');
INSERT INTO INGREDIENT (ID,name, category) VALUES ('7','Faschiertes','Fleisch');
INSERT INTO INGREDIENT (ID,name, category) VALUES ('8','Olivenöl','Öl');
INSERT INTO INGREDIENT (ID,name, category) VALUES ('9','Karotten','Gemüse');
INSERT INTO INGREDIENT (ID,name, category) VALUES ('10','Zwiebeln','Zwiebel');
INSERT INTO INGREDIENT (ID,name, category) VALUES ('11','Knoblauch','Gewürz');
INSERT INTO INGREDIENT (ID,name, category) VALUES ('12','Tomaten (in Stücke geschnitten)','Gemüse');
INSERT INTO INGREDIENT (ID,name, category)  VALUES ('13','Suppenwürfel','Gewürz');
INSERT INTO INGREDIENT (ID,name, category)  VALUES ('14','Spaghetti','Nudeln');
INSERT INTO INGREDIENT (ID,name, category)  VALUES ('15','Brioche Burger Buns','Brot');
INSERT INTO INGREDIENT (ID,name, category)  VALUES ('16','Blauschimmelkäse','Milchprodukt');
INSERT INTO INGREDIENT (ID,name, category)  VALUES ('17','Salatblätter (gewaschen)','Gemüse');
INSERT INTO INGREDIENT (ID,name, category)  VALUES ('18','Lammfaschiertes','Fleisch');
INSERT INTO INGREDIENT (ID,name, category)  VALUES ('19','Kreuzkümmel','Gewürz');
INSERT INTO INGREDIENT (ID,name, category)  VALUES ('20','Meersalz','Gewürz');
INSERT INTO INGREDIENT (ID,name, category)  VALUES ('21','Pfeffer','Gewürz');
INSERT INTO INGREDIENT (ID,name, category)  VALUES ('22','Zucchini','Gemüse');
INSERT INTO INGREDIENT (ID,name, category)  VALUES ('23','Paprika (rot)','Gemüse');
INSERT INTO INGREDIENT (ID,name, category)  VALUES ('24','Paprika (gelb)','Gemüse');
INSERT INTO INGREDIENT (ID,name, category)  VALUES ('25','Jungzwiebel','Zwiebel');
INSERT INTO INGREDIENT (ID,name, category)  VALUES ('26','Tomatenmark','Sauce');
INSERT INTO INGREDIENT (ID,name, category)  VALUES ('27','Thymian','Gewürz');
INSERT INTO INGREDIENT (ID,name, category)  VALUES ('28','Zucker','Gewürz');
INSERT INTO INGREDIENT (ID,name, category)  VALUES ('29','Wasser','Wasser');
INSERT INTO INGREDIENT (ID,name, category)  VALUES ('30','Nudeln','Nudeln');
INSERT INTO INGREDIENT (ID,name, category)  VALUES ('31','Paprika(grün)','Gemüse');
INSERT INTO INGREDIENT (ID,name, category)  VALUES ('32','Mais','Gemüse');
INSERT INTO INGREDIENT (ID,name, category)  VALUES ('33','Käse','Milchprodukt');
INSERT INTO INGREDIENT (ID,name, category)  VALUES ('34','Schinken','Fleisch');
INSERT INTO INGREDIENT (ID,name, category)  VALUES ('35','Mayonnaise','Sauce');
INSERT INTO INGREDIENT (ID,name, category)  VALUES ('36','Salatgurke','Gemüse');
INSERT INTO INGREDIENT (ID,name, category)  VALUES ('37','Tomate','Gemüse');
INSERT INTO INGREDIENT (ID,name, category)  VALUES ('38','Basilikum','Gewürz');
INSERT INTO INGREDIENT (ID,name, category)  VALUES ('39','Schnittlauch','Gewürz');
INSERT INTO INGREDIENT (ID,name, category)  VALUES ('40','Feta','Milchprodukt');
INSERT INTO INGREDIENT (ID,name, category)  VALUES ('41','Weinessig','Essig');
INSERT INTO INGREDIENT (ID,name, category)  VALUES ('42','Rindslungenbraten','Fleisch');
INSERT INTO INGREDIENT (ID,name, category)  VALUES ('43','Champignons','Pilze');
INSERT INTO INGREDIENT (ID,name, category)  VALUES ('44','Essiggurkerl','Gemüse');
INSERT INTO INGREDIENT (ID,name, category)  VALUES ('45','Fond (braun, oder Rindsuppe)','Suppe');
INSERT INTO INGREDIENT (ID,name, category)  VALUES ('46','Sauerrahm','Milchprodukt');
INSERT INTO INGREDIENT (ID,name, category)  VALUES ('47','Öl','Öl');
INSERT INTO INGREDIENT (ID,name, category)  VALUES ('48','Paprikapukver (edelsüß)','Gewürz');
INSERT INTO INGREDIENT (ID,name, category)  VALUES ('49','Spargel (grün)','Gemüse');
INSERT INTO INGREDIENT (ID,name, category)  VALUES ('50','Speck','Fleisch');
INSERT INTO INGREDIENT (ID,name, category)  VALUES ('51','Kartoffeln','Gemüse');
INSERT INTO INGREDIENT (ID,name, category)  VALUES ('52','Stangenbohnen','Bohnen');
INSERT INTO INGREDIENT (ID,name, category)  VALUES ('53','Muskat','Gewürz');
INSERT INTO INGREDIENT (ID,name, category)  VALUES ('54','Hühnerfilet','Fleisch');
INSERT INTO INGREDIENT (ID,name, category)  VALUES ('55','Reis','Reis');
INSERT INTO INGREDIENT (ID,name, category)  VALUES ('56','Gemüsesuppe','Suppe');
INSERT INTO INGREDIENT (ID,name, category)  VALUES ('57','Gemüse (gemischt, nach Marktlage, z.B. Chinakohl, Paprikaschoten, Pak Choi, Zucchini, etc)','Gemüse');
INSERT INTO INGREDIENT (ID,name, category)  VALUES ('58','Chilischoten','Gemüse (scharf)');
INSERT INTO INGREDIENT (ID,name, category)  VALUES ('59','Tofu (geräuchert)','Soja');
INSERT INTO INGREDIENT (ID,name, category)  VALUES ('60','Pflanzenöl','Öl');
INSERT INTO INGREDIENT (ID,name, category)  VALUES ('61','Ingwer','Gewürz');
INSERT INTO INGREDIENT (ID,name, category)  VALUES ('62','Sojasauce','Soja');
INSERT INTO INGREDIENT (ID,name, category)  VALUES ('63','Ahornsirup','Sirup');
INSERT INTO INGREDIENT (ID,name, category)  VALUES ('64','Sesamöl','Öl');
INSERT INTO INGREDIENT (ID,name, category)  VALUES ('65','Sesamkörner','Sesam');
INSERT INTO INGREDIENT (ID,name, category)  VALUES ('66','Huhn','Fleisch');
INSERT INTO INGREDIENT (ID,name, category)  VALUES ('67','Hühnerherzen','Innerei');
INSERT INTO INGREDIENT (ID,name, category)  VALUES ('68','Hühnerleber','Innerei');
INSERT INTO INGREDIENT (ID,name, category)  VALUES ('69','Garnelen','Meeresfrüchte');
INSERT INTO INGREDIENT (ID,name, category)  VALUES ('70','chinesische Pilze','Pilze');
INSERT INTO INGREDIENT (ID,name, category)  VALUES ('71','Lauchstange','Gemüse');
INSERT INTO INGREDIENT (ID,name, category)  VALUES ('72','Erbsenschoten','Gemüse');
INSERT INTO INGREDIENT (ID,name, category)  VALUES ('73','Frühlingszwiebeln','Zwiebel');
INSERT INTO INGREDIENT (ID,name, category)  VALUES ('74','Reiswein','Alkoholhaltiges');
INSERT INTO INGREDIENT (ID,name, category)  VALUES ('75','Sternanis','Gewürz');
INSERT INTO INGREDIENT (ID,name, category)  VALUES ('76','Honig','Nektar');
INSERT INTO INGREDIENT (ID,name, category)  VALUES ('77','Maisstärke','Stärke');
INSERT INTO INGREDIENT (ID,name, category)  VALUES ('78','Wantan-Teigblätter','Teigware');
INSERT INTO INGREDIENT (ID,name, category)  VALUES ('79','Faschiertes Schweinefleisch','Fleisch');
INSERT INTO INGREDIENT (ID,name, category)  VALUES ('80','Shrimps- und/ oder Krebsfleisch','Meeresfrüchte');
INSERT INTO INGREDIENT (ID,name, category)  VALUES ('81','Speisestärke','Stärke');
INSERT INTO INGREDIENT (ID,name, category)  VALUES ('82','Frisch gehacktes Koriandergrün','Gewürz');
INSERT INTO INGREDIENT (ID,name, category)  VALUES ('83','Büffelmozzarella','Milchprodukt');
INSERT INTO INGREDIENT (ID,name, category)  VALUES ('84','Tomaten','Gemüse');
INSERT INTO INGREDIENT (ID,name, category)  VALUES ('85','Balsamicoessig','Essig');
INSERT INTO INGREDIENT (ID,name, category)  VALUES ('86','Schnitzel (groß, vom Schwein, Kalb oder Hühner)','Fleisch');
INSERT INTO INGREDIENT (ID,name, category)  VALUES ('87','Käse (Emmentaler oder Gouda)','Milchprodukt');
INSERT INTO INGREDIENT (ID,name, category)  VALUES ('88','Erdäpfel','Gemüse');
INSERT INTO INGREDIENT (ID,name, category)  VALUES ('89','Semmelbrösel','Brot');
INSERT INTO INGREDIENT (ID,name, category)  VALUES ('90','Zitrone','Zitrus');
INSERT INTO INGREDIENT (ID,name, category)  VALUES ('90','Entenbrust','Fleisch');
INSERT INTO INGREDIENT (ID,name, category)  VALUES ('91','Schalotten','Zwiebel');
INSERT INTO INGREDIENT (ID,name, category)  VALUES ('92','Butterschmalz','Milchprodukt');
INSERT INTO INGREDIENT (ID,name, category)  VALUES ('93','Noilly Prat','Alkoholhaltiges');
INSERT INTO INGREDIENT (ID,name, category)  VALUES ('94','Weißwein','Alkoholhaltiges');
INSERT INTO INGREDIENT (ID,name, category)  VALUES ('95','Schlagobers','Milchprodukt');
INSERT INTO INGREDIENT (ID,name, category)  VALUES ('96','Creme fraiche','Milchprodukt');
INSERT INTO INGREDIENT (ID,name, category)  VALUES ('97','Gänseleber','Innerei');
INSERT INTO INGREDIENT (ID,name, category)  VALUES ('98','Trüffel','Pilze');
INSERT INTO INGREDIENT (ID,name, category)  VALUES ('99','Birne','Obst');
INSERT INTO INGREDIENT (ID,name, category)  VALUES ('100','Zitronensaft','Zitrus');
INSERT INTO INGREDIENT (ID,name, category)  VALUES ('101','Senf','Sauce');
INSERT INTO INGREDIENT (ID,name, category)  VALUES ('102','Mürbteig','Teigware');
INSERT INTO INGREDIENT (ID,name, category)  VALUES ('103','Emmentaler','Milchprodukt');
INSERT INTO INGREDIENT (ID,name, category)  VALUES ('104','Mascarpone','Milchprodukt');
INSERT INTO INGREDIENT (ID,name, category)  VALUES ('105','Lauch','Gemüse');
INSERT INTO INGREDIENT (ID,name, category)  VALUES ('106','Zucchino (kleiner gelber)','Gemüse');
INSERT INTO INGREDIENT (ID,name, category)  VALUES ('107','Beerentomaten','Gemüse');
INSERT INTO INGREDIENT (ID,name, category)  VALUES ('108','Tortillas','Teigware');
INSERT INTO INGREDIENT (ID,name, category)  VALUES ('109','Hühnerschnitzel','Fleisch');
INSERT INTO INGREDIENT (ID,name, category)  VALUES ('110','Käse','Milchprodukt');
INSERT INTO INGREDIENT (ID,name, category)  VALUES ('111','Salsa','Sauce');
INSERT INTO INGREDIENT (ID,name, category)  VALUES ('112','Mayonnaise','Sauce');
INSERT INTO INGREDIENT (ID,name, category)  VALUES ('113','Kidneybohnen','Bohnen');
INSERT INTO INGREDIENT (ID,name, category)  VALUES ('114','Chilipulver','Gewürz');
INSERT INTO INGREDIENT (ID,name, category)  VALUES ('115','Lorbeerblatt','Gewürz');
INSERT INTO INGREDIENT (ID,name, category)  VALUES ('116','Oregano','Gewürz');
INSERT INTO INGREDIENT (ID,name, category)  VALUES ('117','Rindsuppe','Suppe');
INSERT INTO INGREDIENT (ID,name, category)  VALUES ('118','Haferflocken','Kornprodukt');
INSERT INTO INGREDIENT (ID,name, category)  VALUES ('119','Joghurt','Milchprodukt');
INSERT INTO INGREDIENT (ID,name, category)  VALUES ('120','Zimt','Gewürz');
INSERT INTO INGREDIENT (ID,name, category)  VALUES ('121','Staubzucker','Gewürz');
INSERT INTO INGREDIENT (ID,name, category)  VALUES ('122','Buttermilch','Milchprodukt');
INSERT INTO INGREDIENT (ID,name, category)  VALUES ('123','Vanillezucker','Gewürz');
INSERT INTO INGREDIENT (ID,name, category)  VALUES ('124','Topfen','Milchprodukt');
INSERT INTO INGREDIENT (ID,name, category)  VALUES ('125','Marmelade','Marmelade');
INSERT INTO INGREDIENT (ID,name, category)  VALUES ('126','Kürbiskernöl','Öl');
INSERT INTO INGREDIENT (ID,name, category)  VALUES ('127','Radieschen','Gemüse');
INSERT INTO INGREDIENT (ID,name, category)  VALUES ('128','Thunfisch','Fisch');
INSERT INTO INGREDIENT (ID,name, category)  VALUES ('129','Apfelessig','Essig');
INSERT INTO INGREDIENT (ID,name, category)  VALUES ('130','Cocktailtomaten','Gemüse');
INSERT INTO INGREDIENT (ID,name, category)  VALUES ('131','Melone','Obst');
INSERT INTO INGREDIENT (ID,name, category)  VALUES ('132','Gartenkresse','Kräuter');
INSERT INTO INGREDIENT (ID,name, category)  VALUES ('133','Vogerlsalat','Gemüse');
INSERT INTO INGREDIENT (ID,name, category)  VALUES ('134','Stelze (hintere Stelze vom Schwein)','Fleisch');
INSERT INTO INGREDIENT (ID,name, category)  VALUES ('135','Tagliatelle','Nudeln');
INSERT INTO INGREDIENT (ID,name, category)  VALUES ('136','Lachs','Fisch');
INSERT INTO INGREDIENT (ID,name, category)  VALUES ('137','Schweinsrippchen','Fleisch');
INSERT INTO INGREDIENT (ID,name, category)  VALUES ('138','Volkornbrot','Brot');
INSERT INTO INGREDIENT (ID,name, category)  VALUES ('139','Petersilie','Kräuter');
INSERT INTO INGREDIENT (ID,name, category)  VALUES ('140','scharfe Paprika','Gemüse (scharf)');
INSERT INTO INGREDIENT (ID,name, category)  VALUES ('141','Butter','Milchprodukt');
INSERT INTO INGREDIENT (ID,name, category)  VALUES ('142','Salat','Gemüse');