INSERT INTO INGREDIENT (ID,name, category, allergenId) VALUES ('1','Mehl (glatt)','Kornprodukt','1');
INSERT INTO INGREDIENT (ID,name, category, allergenId) VALUES ('2','Eier','Ei','3');
INSERT INTO INGREDIENT (ID,name, category, allergenId) VALUES ('3','Milch','Milchprodukt','7');
INSERT INTO INGREDIENT (ID,name, category, allergenId) VALUES ('4','Butter (geschmolzen)','Milchprodukt','7');
INSERT INTO INGREDIENT (ID,name, category, allergenId) VALUES ('5','Salz','Gewürz','-1');
INSERT INTO INGREDIENT (ID,name, category, allergenId) VALUES ('6','EL Butter (zerlassen, zum Herausbacken)','Milchprodukt','7');
INSERT INTO INGREDIENT (ID,name, category, allergenId) VALUES ('7','Faschiertes','Fleisch','-1');
INSERT INTO INGREDIENT (ID,name, category, allergenId) VALUES ('8','Olivenöl','Öl','-1');
INSERT INTO INGREDIENT (ID,name, category, allergenId) VALUES ('9','Karotten','Gemüse','-1');
INSERT INTO INGREDIENT (ID,name, category, allergenId) VALUES ('10','Zwiebeln','Zwiebel','-1');
INSERT INTO INGREDIENT (ID,name, category, allergenId) VALUES ('11','Knoblauch','Gewürz','-1');
INSERT INTO INGREDIENT (ID,name, category, allergenId) VALUES ('12','Tomaten (in Stücke geschnitten)','Gemüse','-1');
INSERT INTO INGREDIENT (ID,name, category, allergenId)  VALUES ('13','Suppenwürfel','Gewürz','1');
INSERT INTO INGREDIENT (ID,name, category, allergenId)  VALUES ('14','Spaghetti','Nudeln','1');
INSERT INTO INGREDIENT (ID,name, category, allergenId)  VALUES ('15','Brioche Burger Buns','Brot','1');
INSERT INTO INGREDIENT (ID,name, category, allergenId)  VALUES ('16','Blauschimmelkäse','Milchprodukt','7');
INSERT INTO INGREDIENT (ID,name, category, allergenId)  VALUES ('17','Salatblätter (gewaschen)','Gemüse','-1');
INSERT INTO INGREDIENT (ID,name, category, allergenId)  VALUES ('18','Lammfaschiertes','Fleisch','-1');
INSERT INTO INGREDIENT (ID,name, category, allergenId)  VALUES ('19','Kreuzkümmel','Gewürz','-1');
INSERT INTO INGREDIENT (ID,name, category, allergenId)  VALUES ('20','Meersalz','Gewürz','-1');
INSERT INTO INGREDIENT (ID,name, category, allergenId)  VALUES ('21','Pfeffer','Gewürz','-1');
INSERT INTO INGREDIENT (ID,name, category, allergenId)  VALUES ('22','Zucchini','Gemüse','-1');
INSERT INTO INGREDIENT (ID,name, category, allergenId)  VALUES ('23','Paprika (rot)','Gemüse','-1');
INSERT INTO INGREDIENT (ID,name, category, allergenId)  VALUES ('24','Paprika (gelb)','Gemüse','-1');
INSERT INTO INGREDIENT (ID,name, category, allergenId)  VALUES ('25','Jungzwiebel','Zwiebel','-1');
INSERT INTO INGREDIENT (ID,name, category, allergenId)  VALUES ('26','Tomatenmark','Sauce','-1');
INSERT INTO INGREDIENT (ID,name, category, allergenId)  VALUES ('27','Thymian','Gewürz','-1');
INSERT INTO INGREDIENT (ID,name, category, allergenId)  VALUES ('28','Zucker','Gewürz','-1');
INSERT INTO INGREDIENT (ID,name, category, allergenId)  VALUES ('29','Wasser','Wasser','-1');
INSERT INTO INGREDIENT (ID,name, category, allergenId)  VALUES ('30','Nudeln','Nudeln','1');
INSERT INTO INGREDIENT (ID,name, category, allergenId)  VALUES ('31','Paprika(grün)','Gemüse','-1');
INSERT INTO INGREDIENT (ID,name, category, allergenId)  VALUES ('32','Mais','Gemüse','-1');
INSERT INTO INGREDIENT (ID,name, category, allergenId)  VALUES ('33','Käse','Milchprodukt','7');
INSERT INTO INGREDIENT (ID,name, category, allergenId)  VALUES ('34','Schinken','Fleisch','-1');
INSERT INTO INGREDIENT (ID,name, category, allergenId)  VALUES ('35','Mayonnaise','Sauce','3');
INSERT INTO INGREDIENT (ID,name, category, allergenId)  VALUES ('36','Salatgurke','Gemüse','-1');
INSERT INTO INGREDIENT (ID,name, category, allergenId)  VALUES ('37','Tomate','Gemüse','-1');
INSERT INTO INGREDIENT (ID,name, category, allergenId)  VALUES ('38','Basilikum','Gewürz','-1');
INSERT INTO INGREDIENT (ID,name, category, allergenId)  VALUES ('39','Schnittlauch','Gewürz','-1');
INSERT INTO INGREDIENT (ID,name, category, allergenId)  VALUES ('40','Feta','Milchprodukt','7');
INSERT INTO INGREDIENT (ID,name, category, allergenId)  VALUES ('41','Weinessig','Essig','12');
INSERT INTO INGREDIENT (ID,name, category, allergenId)  VALUES ('42','Rindslungenbraten','Fleisch','-1');
INSERT INTO INGREDIENT (ID,name, category, allergenId)  VALUES ('43','Champignons','Pilze','-1');
INSERT INTO INGREDIENT (ID,name, category, allergenId)  VALUES ('44','Essiggurkerl','Gemüse','10');
INSERT INTO INGREDIENT (ID,name, category, allergenId)  VALUES ('45','Fond (braun, oder Rindsuppe)','Suppe','1');
INSERT INTO INGREDIENT (ID,name, category, allergenId)  VALUES ('46','Sauerrahm','Milchprodukt','7');
INSERT INTO INGREDIENT (ID,name, category, allergenId)  VALUES ('47','Öl','Öl','-1');
INSERT INTO INGREDIENT (ID,name, category, allergenId)  VALUES ('48','Paprikapukver (edelsüß)','Gewürz','-1');
INSERT INTO INGREDIENT (ID,name, category, allergenId)  VALUES ('49','Spargel (grün)','Gemüse','-1');
INSERT INTO INGREDIENT (ID,name, category, allergenId)  VALUES ('50','Speck','Fleisch','-1');
INSERT INTO INGREDIENT (ID,name, category, allergenId)  VALUES ('51','Kartoffeln','Gemüse','-1');
INSERT INTO INGREDIENT (ID,name, category, allergenId)  VALUES ('52','Stangenbohnen','Bohnen','-1');
INSERT INTO INGREDIENT (ID,name, category, allergenId)  VALUES ('53','Muskat','Gewürz','-1');
INSERT INTO INGREDIENT (ID,name, category, allergenId)  VALUES ('54','Hühnerfilet','Fleisch','-1');
INSERT INTO INGREDIENT (ID,name, category, allergenId)  VALUES ('55','Reis','Reis','-1');
INSERT INTO INGREDIENT (ID,name, category, allergenId)  VALUES ('56','Gemüsesuppe','Suppe','9');
INSERT INTO INGREDIENT (ID,name, category, allergenId)  VALUES ('57','Gemüse (gemischt, nach Marktlage, z.B. Chinakohl, Paprikaschoten, Pak Choi, Zucchini, etc)','Gemüse','');
INSERT INTO INGREDIENT (ID,name, category, allergenId)  VALUES ('58','Chilischoten','Gemüse (scharf)','-1');
INSERT INTO INGREDIENT (ID,name, category, allergenId)  VALUES ('59','Tofu (geräuchert)','Soja','6');
INSERT INTO INGREDIENT (ID,name, category, allergenId)  VALUES ('60','Pflanzenöl','Öl','-1');
INSERT INTO INGREDIENT (ID,name, category, allergenId)  VALUES ('61','Ingwer','Gewürz','-1');
INSERT INTO INGREDIENT (ID,name, category, allergenId)  VALUES ('62','Sojasauce','Soja','6');
INSERT INTO INGREDIENT (ID,name, category, allergenId)  VALUES ('63','Ahornsirup','Sirup','-1');
INSERT INTO INGREDIENT (ID,name, category, allergenId)  VALUES ('64','Sesamöl','Öl','11');
INSERT INTO INGREDIENT (ID,name, category, allergenId)  VALUES ('65','Sesamkörner','Sesam','11');
INSERT INTO INGREDIENT (ID,name, category, allergenId)  VALUES ('66','Huhn','Fleisch','-1');
INSERT INTO INGREDIENT (ID,name, category, allergenId)  VALUES ('67','Hühnerherzen','Innerei','-1');
INSERT INTO INGREDIENT (ID,name, category, allergenId)  VALUES ('68','Hühnerleber','Innerei','-1');
INSERT INTO INGREDIENT (ID,name, category, allergenId)  VALUES ('69','Garnelen','Meeresfrüchte','2');
INSERT INTO INGREDIENT (ID,name, category, allergenId)  VALUES ('70','chinesische Pilze','Pilze','-1');
INSERT INTO INGREDIENT (ID,name, category, allergenId)  VALUES ('71','Lauchstange','Gemüse','-1');
INSERT INTO INGREDIENT (ID,name, category, allergenId)  VALUES ('72','Erbsenschoten','Gemüse','-1');
INSERT INTO INGREDIENT (ID,name, category, allergenId)  VALUES ('73','Frühlingszwiebeln','Zwiebel','-1');
INSERT INTO INGREDIENT (ID,name, category, allergenId)  VALUES ('74','Reiswein','Alkoholhaltiges','12');
INSERT INTO INGREDIENT (ID,name, category, allergenId)  VALUES ('75','Sternanis','Gewürz','-1');
INSERT INTO INGREDIENT (ID,name, category, allergenId)  VALUES ('76','Honig','Nektar','-1');
INSERT INTO INGREDIENT (ID,name, category, allergenId)  VALUES ('77','Maisstärke','Stärke','-1');
INSERT INTO INGREDIENT (ID,name, category, allergenId)  VALUES ('78','Wantan-Teigblätter','Teigware','1');
INSERT INTO INGREDIENT (ID,name, category, allergenId)  VALUES ('79','Faschiertes Schweinefleisch','Fleisch','-1');
INSERT INTO INGREDIENT (ID,name, category, allergenId)  VALUES ('80','Shrimps- und/ oder Krebsfleisch','Meeresfrüchte','2');
INSERT INTO INGREDIENT (ID,name, category, allergenId)  VALUES ('81','Speisestärke','Stärke','-1');
INSERT INTO INGREDIENT (ID,name, category, allergenId)  VALUES ('82','Frisch gehacktes Koriandergrün','Gewürz','-1');
INSERT INTO INGREDIENT (ID,name, category, allergenId)  VALUES ('83','Büffelmozzarella','Milchprodukt','7');
INSERT INTO INGREDIENT (ID,name, category, allergenId)  VALUES ('84','Tomaten','Gemüse','-1');
INSERT INTO INGREDIENT (ID,name, category, allergenId)  VALUES ('85','Balsamicoessig','Essig','12');
INSERT INTO INGREDIENT (ID,name, category, allergenId)  VALUES ('86','Schnitzel (groß, vom Schwein, Kalb oder Hühner)','Fleisch','-1');
INSERT INTO INGREDIENT (ID,name, category, allergenId)  VALUES ('87','Käse (Emmentaler oder Gouda)','Milchprodukt','7');
INSERT INTO INGREDIENT (ID,name, category, allergenId)  VALUES ('88','Erdäpfel','Gemüse','-1');
INSERT INTO INGREDIENT (ID,name, category, allergenId)  VALUES ('89','Semmelbrösel','Brot','1');
INSERT INTO INGREDIENT (ID,name, category, allergenId)  VALUES ('90','Zitrone','Zitrus','-1');
INSERT INTO INGREDIENT (ID,name, category, allergenId)  VALUES ('90','Entenbrust','Fleisch','-1');
INSERT INTO INGREDIENT (ID,name, category, allergenId)  VALUES ('91','Schalotten','Zwiebel','-1');
INSERT INTO INGREDIENT (ID,name, category, allergenId)  VALUES ('92','Butterschmalz','Milchprodukt','7');
INSERT INTO INGREDIENT (ID,name, category, allergenId)  VALUES ('93','Noilly Prat','Alkoholhaltiges','12');
INSERT INTO INGREDIENT (ID,name, category, allergenId)  VALUES ('94','Weißwein','Alkoholhaltiges','12');
INSERT INTO INGREDIENT (ID,name, category, allergenId)  VALUES ('95','Schlagobers','Milchprodukt','7');
INSERT INTO INGREDIENT (ID,name, category, allergenId)  VALUES ('96','Creme fraiche','Milchprodukt','7');
INSERT INTO INGREDIENT (ID,name, category, allergenId)  VALUES ('97','Gänseleber','Innerei','-1');
INSERT INTO INGREDIENT (ID,name, category, allergenId)  VALUES ('98','Trüffel','Pilze','-1');
INSERT INTO INGREDIENT (ID,name, category, allergenId)  VALUES ('99','Birne','Obst','-1');
INSERT INTO INGREDIENT (ID,name, category, allergenId)  VALUES ('100','Zitronensaft','Zitrus','-1');
INSERT INTO INGREDIENT (ID,name, category, allergenId)  VALUES ('101','Senf','Sauce','10');
INSERT INTO INGREDIENT (ID,name, category, allergenId)  VALUES ('102','Mürbteig','Teigware','1');
INSERT INTO INGREDIENT (ID,name, category, allergenId)  VALUES ('103','Emmentaler','Milchprodukt','7');
INSERT INTO INGREDIENT (ID,name, category, allergenId)  VALUES ('104','Mascarpone','Milchprodukt','7');
INSERT INTO INGREDIENT (ID,name, category, allergenId)  VALUES ('105','Lauch','Gemüse','-1');
INSERT INTO INGREDIENT (ID,name, category, allergenId)  VALUES ('106','Zucchino (kleiner gelber)','Gemüse','-1');
INSERT INTO INGREDIENT (ID,name, category, allergenId)  VALUES ('107','Beerentomaten','Gemüse','-1');
INSERT INTO INGREDIENT (ID,name, category, allergenId)  VALUES ('108','Tortillas','Teigware','1');
INSERT INTO INGREDIENT (ID,name, category, allergenId)  VALUES ('109','Hühnerschnitzel','Fleisch','-1');
INSERT INTO INGREDIENT (ID,name, category, allergenId)  VALUES ('110','Käse','Milchprodukt','7');
INSERT INTO INGREDIENT (ID,name, category, allergenId)  VALUES ('111','Salsa','Sauce','12');
INSERT INTO INGREDIENT (ID,name, category, allergenId)  VALUES ('112','Mayonnaise','Sauce','3');
INSERT INTO INGREDIENT (ID,name, category, allergenId)  VALUES ('113','Kidneybohnen','Bohnen','-1');
INSERT INTO INGREDIENT (ID,name, category, allergenId)  VALUES ('114','Chilipulver','Gewürz','-1');
INSERT INTO INGREDIENT (ID,name, category, allergenId)  VALUES ('115','Lorbeerblatt','Gewürz','-1');
INSERT INTO INGREDIENT (ID,name, category, allergenId)  VALUES ('116','Oregano','Gewürz','-1');
INSERT INTO INGREDIENT (ID,name, category, allergenId)  VALUES ('117','Rindsuppe','Suppe','1');
INSERT INTO INGREDIENT (ID,name, category, allergenId)  VALUES ('118','Haferflocken','Kornprodukt','1');
INSERT INTO INGREDIENT (ID,name, category, allergenId)  VALUES ('119','Joghurt','Milchprodukt','7');
INSERT INTO INGREDIENT (ID,name, category, allergenId)  VALUES ('120','Zimt','Gewürz','-1');
INSERT INTO INGREDIENT (ID,name, category, allergenId)  VALUES ('121','Staubzucker','Gewürz','-1');
INSERT INTO INGREDIENT (ID,name, category, allergenId)  VALUES ('122','Buttermilch','Milchprodukt','7');
INSERT INTO INGREDIENT (ID,name, category, allergenId)  VALUES ('123','Vanillezucker','Gewürz','-1');
INSERT INTO INGREDIENT (ID,name, category, allergenId)  VALUES ('124','Topfen','Milchprodukt','7');
INSERT INTO INGREDIENT (ID,name, category, allergenId)  VALUES ('125','Marmelade','Marmelade','-1');
INSERT INTO INGREDIENT (ID,name, category, allergenId)  VALUES ('126','Kürbiskernöl','Öl','-1');
INSERT INTO INGREDIENT (ID,name, category, allergenId)  VALUES ('127','Radieschen','Gemüse','-1');
INSERT INTO INGREDIENT (ID,name, category, allergenId)  VALUES ('128','Thunfisch','Fisch','4');
INSERT INTO INGREDIENT (ID,name, category, allergenId)  VALUES ('129','Apfelessig','Essig','12');
INSERT INTO INGREDIENT (ID,name, category, allergenId)  VALUES ('130','Cocktailtomaten','Gemüse','-1');
INSERT INTO INGREDIENT (ID,name, category, allergenId)  VALUES ('131','Melone','Obst','-1');
INSERT INTO INGREDIENT (ID,name, category, allergenId)  VALUES ('132','Gartenkresse','Kräuter','-1');
INSERT INTO INGREDIENT (ID,name, category, allergenId)  VALUES ('133','Vogerlsalat','Gemüse','-1');
INSERT INTO INGREDIENT (ID,name, category, allergenId)  VALUES ('134','Stelze (hintere Stelze vom Schwein)','Fleisch','-1');
INSERT INTO INGREDIENT (ID,name, category, allergenId)  VALUES ('135','Tagliatelle','Nudeln','1');
INSERT INTO INGREDIENT (ID,name, category, allergenId)  VALUES ('136','Lachs','Fisch','4');
INSERT INTO INGREDIENT (ID,name, category, allergenId)  VALUES ('137','Schweinsrippchen','Fleisch','-1');
INSERT INTO INGREDIENT (ID,name, category, allergenId)  VALUES ('138','Volkornbrot','Brot','1');
INSERT INTO INGREDIENT (ID,name, category, allergenId)  VALUES ('139','Petersilie','Kräuter','-1');
INSERT INTO INGREDIENT (ID,name, category, allergenId)  VALUES ('140','scharfe Paprika','Gemüse (scharf)','-1');
INSERT INTO INGREDIENT (ID,name, category, allergenId)  VALUES ('141','Butter','Milchprodukt','7');
INSERT INTO INGREDIENT (ID,name, category, allergenId)  VALUES ('142','Salat','Gemüse','-1');