INSERT INTO INGREDIENT (name, category) VALUES ('Mehl (glatt)','Kornprodukt');
INSERT INTO INGREDIENT (name, category) VALUES ('Eier','Ei');
INSERT INTO INGREDIENT (name, category) VALUES ('Milch','Milchprodukt');
INSERT INTO INGREDIENT (name, category) VALUES ('Butter (geschmolzen)','Milchprodukt');
INSERT INTO INGREDIENT (name, category) VALUES ('Salz','Gewürz');
INSERT INTO INGREDIENT (name, category) VALUES ('EL Butter (zerlassen, zum Herausbacken)','Milchprodukt');
INSERT INTO INGREDIENT (name, category) VALUES ('Faschiertes','Fleisch');
INSERT INTO INGREDIENT (name, category) VALUES ('Olivenöl','Öl');
INSERT INTO INGREDIENT (name, category) VALUES ('Karotten','Gemüse');
INSERT INTO INGREDIENT (name, category) VALUES ('Zwiebeln','Zwiebel');
INSERT INTO INGREDIENT (name, category) VALUES ('Knoblauch','Gewürz');
INSERT INTO INGREDIENT (name, category) VALUES ('Tomaten (in Stücke geschnitten)','Gemüse');
INSERT INTO INGREDIENT (name, category)  VALUES ('Suppenwürfel','Gewürz');
INSERT INTO INGREDIENT (name, category)  VALUES ('Spaghetti','Nudeln');
INSERT INTO INGREDIENT (name, category)  VALUES ('Brioche Burger Buns','Brot');
INSERT INTO INGREDIENT (name, category)  VALUES ('Blauschimmelkäse','Milchprodukt');
INSERT INTO INGREDIENT (name, category)  VALUES ('Salatblätter (gewaschen)','Gemüse');
INSERT INTO INGREDIENT (name, category)  VALUES ('Lammfaschiertes','Fleisch');
INSERT INTO INGREDIENT (name, category)  VALUES ('Kreuzkümmel','Gewürz');
INSERT INTO INGREDIENT (name, category)  VALUES ('Meersalz','Gewürz');
INSERT INTO INGREDIENT (name, category)  VALUES ('Pfeffer','Gewürz');
INSERT INTO INGREDIENT (name, category)  VALUES ('Zucchini','Gemüse');
INSERT INTO INGREDIENT (name, category)  VALUES ('Paprika (rot)','Gemüse');
INSERT INTO INGREDIENT (name, category)  VALUES ('Paprika (gelb)','Gemüse');
INSERT INTO INGREDIENT (name, category)  VALUES ('Jungzwiebel','Zwiebel');
INSERT INTO INGREDIENT (name, category)  VALUES ('Tomatenmark','Sauce');
INSERT INTO INGREDIENT (name, category)  VALUES ('Thymian','Gewürz');
INSERT INTO INGREDIENT (name, category)  VALUES ('Zucker','Gewürz');
INSERT INTO INGREDIENT (name, category)  VALUES ('Wasser','Wasser');
INSERT INTO INGREDIENT (name, category)  VALUES ('Nudeln','Nudeln');
INSERT INTO INGREDIENT (name, category)  VALUES ('Paprika(grün)','Gemüse');
INSERT INTO INGREDIENT (name, category)  VALUES ('Mais','Gemüse');
INSERT INTO INGREDIENT (name, category)  VALUES ('Käse','Milchprodukt');
INSERT INTO INGREDIENT (name, category)  VALUES ('Schinken','Fleisch');
INSERT INTO INGREDIENT (name, category)  VALUES ('Mayonnaise','Sauce');
INSERT INTO INGREDIENT (name, category)  VALUES ('Salatgurke','Gemüse');
INSERT INTO INGREDIENT (name, category)  VALUES ('Tomate','Gemüse');
INSERT INTO INGREDIENT (name, category)  VALUES ('Basilikum','Gewürz');
INSERT INTO INGREDIENT (name, category)  VALUES ('Schnittlauch','Gewürz');
INSERT INTO INGREDIENT (name, category)  VALUES ('Feta','Milchprodukt');
INSERT INTO INGREDIENT (name, category)  VALUES ('Weinessig','Essig');
INSERT INTO INGREDIENT (name, category)  VALUES ('Rindslungenbraten','Fleisch');
INSERT INTO INGREDIENT (name, category)  VALUES ('Champignons','Pilze');
INSERT INTO INGREDIENT (name, category)  VALUES ('Essiggurkerl','Gemüse');
INSERT INTO INGREDIENT (name, category)  VALUES ('Fond (braun, oder Rindsuppe)','Suppe');
INSERT INTO INGREDIENT (name, category)  VALUES ('Sauerrahm','Milchprodukt');
INSERT INTO INGREDIENT (name, category)  VALUES ('Öl','Öl');
INSERT INTO INGREDIENT (name, category)  VALUES ('Paprikapukver (edelsüß)','Gewürz');
INSERT INTO INGREDIENT (name, category)  VALUES ('Spargel (grün)','Gemüse');
INSERT INTO INGREDIENT (name, category)  VALUES ('Speck','Fleisch');
INSERT INTO INGREDIENT (name, category)  VALUES ('Kartoffeln','Gemüse');
INSERT INTO INGREDIENT (name, category)  VALUES ('Stangenbohnen','Bohnen');
INSERT INTO INGREDIENT (name, category)  VALUES ('Muskat','Gewürz');
INSERT INTO INGREDIENT (name, category)  VALUES ('Hühnerfilet','Fleisch');
INSERT INTO INGREDIENT (name, category)  VALUES ('Reis','Reis');
INSERT INTO INGREDIENT (name, category)  VALUES ('Gemüsesuppe','Suppe');
INSERT INTO INGREDIENT (name, category)  VALUES ('Gemüse (gemischt, nach Marktlage, z.B. Chinakohl, Paprikaschoten, Pak Choi, Zucchini, etc)','Gemüse');
INSERT INTO INGREDIENT (name, category)  VALUES ('Chilischoten','Gemüse (scharf)');
INSERT INTO INGREDIENT (name, category)  VALUES ('Tofu (geräuchert)','Soja');
INSERT INTO INGREDIENT (name, category)  VALUES ('Pflanzenöl','Öl');
INSERT INTO INGREDIENT (name, category)  VALUES ('Ingwer','Gewürz');
INSERT INTO INGREDIENT (name, category)  VALUES ('Sojasauce','Soja');
INSERT INTO INGREDIENT (name, category)  VALUES ('Ahornsirup','Sirup');
INSERT INTO INGREDIENT (name, category)  VALUES ('Sesamöl','Öl');
INSERT INTO INGREDIENT (name, category)  VALUES ('Sesamkörner','Sesam');
INSERT INTO INGREDIENT (name, category)  VALUES ('Huhn','Fleisch');
INSERT INTO INGREDIENT (name, category)  VALUES ('Hühnerherzen','Innerei');
INSERT INTO INGREDIENT (name, category)  VALUES ('Hühnerleber','Innerei');
INSERT INTO INGREDIENT (name, category)  VALUES ('Garnelen','Meeresfrüchte');
INSERT INTO INGREDIENT (name, category)  VALUES ('chinesische Pilze','Pilze');
INSERT INTO INGREDIENT (name, category)  VALUES ('Lauchstange','Gemüse');
INSERT INTO INGREDIENT (name, category)  VALUES ('Erbsenschoten','Gemüse');
INSERT INTO INGREDIENT (name, category)  VALUES ('Frühlingszwiebeln','Zwiebel');
INSERT INTO INGREDIENT (name, category)  VALUES ('Reiswein','Alkoholhaltiges');
INSERT INTO INGREDIENT (name, category)  VALUES ('Sternanis','Gewürz');
INSERT INTO INGREDIENT (name, category)  VALUES ('Honig','Nektar');
INSERT INTO INGREDIENT (name, category)  VALUES ('Maisstärke','Stärke');
INSERT INTO INGREDIENT (name, category)  VALUES ('Wantan-Teigblätter','Teigware');
INSERT INTO INGREDIENT (name, category)  VALUES ('Faschiertes Schweinefleisch','Fleisch');
INSERT INTO INGREDIENT (name, category)  VALUES ('Shrimps- und/ oder Krebsfleisch','Meeresfrüchte');
INSERT INTO INGREDIENT (name, category)  VALUES ('Speisestärke','Stärke');
INSERT INTO INGREDIENT (name, category)  VALUES ('Frisch gehacktes Koriandergrün','Gewürz');
INSERT INTO INGREDIENT (name, category)  VALUES ('Büffelmozzarella','Milchprodukt');
INSERT INTO INGREDIENT (name, category)  VALUES ('Tomaten','Gemüse');
INSERT INTO INGREDIENT (name, category)  VALUES ('Balsamicoessig','Essig');
INSERT INTO INGREDIENT (name, category)  VALUES ('Schnitzel (groß, vom Schwein, Kalb oder Hühner)','Fleisch');
INSERT INTO INGREDIENT (name, category)  VALUES ('Käse (Emmentaler oder Gouda)','Milchprodukt');
INSERT INTO INGREDIENT (name, category)  VALUES ('Erdäpfel','Gemüse');
INSERT INTO INGREDIENT (name, category)  VALUES ('Semmelbrösel','Brot');
INSERT INTO INGREDIENT (name, category)  VALUES ('Zitrone','Zitrus');
INSERT INTO INGREDIENT (name, category)  VALUES ('Entenbrust','Fleisch');
INSERT INTO INGREDIENT (name, category)  VALUES ('Schalotten','Zwiebel');
INSERT INTO INGREDIENT (name, category)  VALUES ('Butterschmalz','Milchprodukt');
INSERT INTO INGREDIENT (name, category)  VALUES ('Noilly Prat','Alkoholhaltiges');
INSERT INTO INGREDIENT (name, category)  VALUES ('Weißwein','Alkoholhaltiges');
INSERT INTO INGREDIENT (name, category)  VALUES ('Schlagobers','Milchprodukt');
INSERT INTO INGREDIENT (name, category)  VALUES ('Creme fraiche','Milchprodukt');
INSERT INTO INGREDIENT (name, category)  VALUES ('Gänseleber','Innerei');
INSERT INTO INGREDIENT (name, category)  VALUES ('Trüffel','Pilze');
INSERT INTO INGREDIENT (name, category)  VALUES ('Birne','Obst');
INSERT INTO INGREDIENT (name, category)  VALUES ('Zitronensaft','Zitrus');
INSERT INTO INGREDIENT (name, category)  VALUES ('Senf','Sauce');
INSERT INTO INGREDIENT (name, category)  VALUES ('Mürbteig','Teigware');
INSERT INTO INGREDIENT (name, category)  VALUES ('Emmentaler','Milchprodukt');
INSERT INTO INGREDIENT (name, category)  VALUES ('Mascarpone','Milchprodukt');
INSERT INTO INGREDIENT (name, category)  VALUES ('Lauch','Gemüse');
INSERT INTO INGREDIENT (name, category)  VALUES ('Zucchino (kleiner gelber)','Gemüse');
INSERT INTO INGREDIENT (name, category)  VALUES ('Beerentomaten','Gemüse');
INSERT INTO INGREDIENT (name, category)  VALUES ('Tortillas','Teigware');
INSERT INTO INGREDIENT (name, category)  VALUES ('Hühnerschnitzel','Fleisch');
INSERT INTO INGREDIENT (name, category)  VALUES ('Käse','Milchprodukt');
INSERT INTO INGREDIENT (name, category)  VALUES ('Salsa','Sauce');
INSERT INTO INGREDIENT (name, category)  VALUES ('Mayonnaise','Sauce');
INSERT INTO INGREDIENT (name, category)  VALUES ('Kidneybohnen','Bohnen');
INSERT INTO INGREDIENT (name, category)  VALUES ('Chilipulver','Gewürz');
INSERT INTO INGREDIENT (name, category)  VALUES ('Lorbeerblatt','Gewürz');
INSERT INTO INGREDIENT (name, category)  VALUES ('Oregano','Gewürz');
INSERT INTO INGREDIENT (name, category)  VALUES ('Rindsuppe','Suppe');
INSERT INTO INGREDIENT (name, category)  VALUES ('Haferflocken','Kornprodukt');
INSERT INTO INGREDIENT (name, category)  VALUES ('Joghurt','Milchprodukt');
INSERT INTO INGREDIENT (name, category)  VALUES ('Zimt','Gewürz');
INSERT INTO INGREDIENT (name, category)  VALUES ('Staubzucker','Gewürz');
INSERT INTO INGREDIENT (name, category)  VALUES ('Buttermilch','Milchprodukt');
INSERT INTO INGREDIENT (name, category)  VALUES ('Vanillezucker','Gewürz');
INSERT INTO INGREDIENT (name, category)  VALUES ('Topfen','Milchprodukt');
INSERT INTO INGREDIENT (name, category)  VALUES ('Marmelade','Marmelade');
INSERT INTO INGREDIENT (name, category)  VALUES ('Kürbiskernöl','Öl');
INSERT INTO INGREDIENT (name, category)  VALUES ('Radieschen','Gemüse');
INSERT INTO INGREDIENT (name, category)  VALUES ('Thunfisch','Fisch');
INSERT INTO INGREDIENT (name, category)  VALUES ('Apfelessig','Essig');
INSERT INTO INGREDIENT (name, category)  VALUES ('Cocktailtomaten','Gemüse');
INSERT INTO INGREDIENT (name, category)  VALUES ('Melone','Obst');
INSERT INTO INGREDIENT (name, category)  VALUES ('Gartenkresse','Kräuter');
INSERT INTO INGREDIENT (name, category)  VALUES ('Vogerlsalat','Gemüse');
INSERT INTO INGREDIENT (name, category)  VALUES ('Stelze (hintere Stelze vom Schwein)','Fleisch');
INSERT INTO INGREDIENT (name, category)  VALUES ('Tagliatelle','Nudeln');
INSERT INTO INGREDIENT (name, category)  VALUES ('Lachs','Fisch');
INSERT INTO INGREDIENT (name, category)  VALUES ('Schweinsrippchen','Fleisch');
INSERT INTO INGREDIENT (name, category)  VALUES ('Volkornbrot','Brot');
INSERT INTO INGREDIENT (name, category)  VALUES ('Petersilie','Kräuter');
INSERT INTO INGREDIENT (name, category)  VALUES ('scharfe Paprika','Gemüse (scharf)');
INSERT INTO INGREDIENT (name, category)  VALUES ('Butter','Milchprodukt');
INSERT INTO INGREDIENT (name, category)  VALUES ('Salat','Gemüse');